### ISSUE TITLE
Add GPU testing

### ISSUE THREAD

**Issue by MilkshakeForReal** [jonniedie/ComponentArrays.jl#152]
The recent issue #150 illustrates the importance of adding GPU testing

**Comment by jonniedie** [comment]
I agree. I used to just explicitly not support GPU ComponentArrays because the way I had broadcasting work made it too difficult. A somewhat recent change simplified broadcasting quite a bit and allowed for it to work. There are still some pretty rough edges, though, as you’ve noticed. Unfortunately, I’m running on an M1 Mac now, so I can’t test CUDA stuff locally. Last I checked, I couldn’t find a free CI service that used GPUs, but admittedly I didn’t look very hard. If you know of anything that fits the bill, let me know.

**Comment by MilkshakeForReal** [comment]
[JLArrays](https://github.com/JuliaGPU/GPUArrays.jl/tree/master/lib/JLArrays) provides fake gpu arrays for testing

**Comment by jonniedie** [comment]
Oh awesome, I’ll check that out, then.

**Comment by MilkshakeForReal** [comment]
You can also take a look at how Lux does this:
https://github.com/avik-pal/Lux.jl/blob/main/test/adapt.jl#L9-L21

**Comment by MilkshakeForReal** [comment]
Closing this since probably no one would do it
