### ISSUE TITLE
Allow missing values in ComponentArray constructor

### ISSUE THREAD

**Issue by metanoid** [jonniedie/ComponentArrays.jl#18]
The following construction fails:
`ComponentArray(a=1, b=[2, 1, 4, missing], c=[1, 2, 3])`

because in `utils.jl` there is no method for `recursive_length(a::Missing)`

**Comment by jonniedie** [comment]
Thanks for these! Data science things like this are a bit of a blind spot for me, so it's good to have people using them to let me know what doesn't work for those workflows.

As of right now, `ComponentArray`s will automatically default to Float64 rather than trying to find a bounding type for all the data passed in. To support other types (including type unions with `Missing`), you can now do `ComponentArray{Union{Float64,Missing}}(a=missing, b=[2, 1, 4, 5], c=[1, 2, 3])`.

**Comment by jonniedie** [comment]
It looks like this fails with ComponentArray{Union{Float64,Missing}}(a=1, b=[2, 1, 4, missing], c=[1, 2, 3]). because I didn't allow heterogeneous array types. Let's keep this open and I'll look into fixing that.

**Comment by jonniedie** [comment]
K, it wasn't too bad of a change. Just needed to look for `Union{Number, Missing}` when making the axes rather than just `Number`. I'll have to write some more tests for `Missing` stuff at some point, but for now I'm going to call this good. If you run into any problems with it, feel free to reopen this issue.

**Comment by jonniedie** [comment]
@JuliaRegistrator register
