### ISSUE TITLE
Multiplication by StaticMatrix is ambiguous

### ISSUE THREAD

**Issue by dcabecinhas** [jonniedie/ComponentArrays.jl#33]
Hi,

I hit this issue when converting some of my code to ComponentArrays, reduced here to an MWE.

```julia
julia> A = @SMatrix [1 2; 3 4]
2×2 SArray{Tuple{2,2},Int64,2,4} with indices SOneTo(2)×SOneTo(2):
 1  2
 3  4

julia> b = ComponentArray( a = 1, b = 2)
ComponentVector{Int64}(a = 1, b = 2)

julia> A*b
ERROR: MethodError: *(::SArray{Tuple{2,2},Int64,2,4}, ::ComponentArray{Int64,1,Array{Int64,1},Tuple{Axis{(a = 1, b = 2)}}}) is ambiguous. Candidates:
  *(A::StaticArray{Tuple{N,M},T,2} where T where M where N, B::AbstractArray{T,1} where T) in StaticArrays at /Users/dcabecinhas/.julia/packages/StaticArrays/mlIi1/src/matrix_multiply.jl:7
  *(x::AbstractArray{T,2} where T, y::ComponentArray) in ComponentArrays at /Users/dcabecinhas/.julia/packages/ComponentArrays/b9u6s/src/math.jl:16
Possible fix, define
  *(::StaticArray{Tuple{N,M},T,2} where T where M where N, ::ComponentArray{T,1,A,Axes} where Axes<:Tuple{Vararg{AbstractAxis,N} where N} where A<:AbstractArray{T,1} where T)
Stacktrace:
 [1] top-level scope at REPL[29]:1
```

**Comment by jonniedie** [comment]
Yikes. I'll have to drop a lot of the linear algebra inner array forwarding because this is going to be a continual problem with array types that similarly overload *, /, \ etc. Thanks for catching this! I'll try to push an update shortly.

**Comment by jonniedie** [comment]
Thankfully those methods only give slight performance improvements. It is well worth it to drop them in favor of avoiding the nightmare of method ambiguities.

**Comment by dcabecinhas** [comment]
Great! Thanks for the fast response and for the package.

**Comment by jonniedie** [comment]
Should be good to go once the Registrator does its thing.

Also, if you want `b` to be a `StaticArray` as well, you can do
```julia
julia> b = ComponentArray{SVector{2,Float64}}( a = 1, b = 2)
ComponentVector{SArray{Tuple{2},Float64,1,2}}(a = 1.0, b = 2.0)
```
I haven't documented this yet because different inner array styles have been pretty buggy in the past due to all the conflicting broadcasting implementations (and StaticArrays seem to be the worst offender). I just pushed an update recently that (hopefully) fixes all of this, though, so feel free to try it out. If you catch issues, they're always welcome.

**Comment by jonniedie** [comment]
It's also worth noting that the `b = ComponentArray{SVector{2,Float64}}( a = 1, b = 2)` style of constructor will allocate because it builds a Vector by pushing values and then converts them to the correct inner array type. So this wouldn't be great in a hot loop. But I'm planning on reworking the constructor anyway because it's pretty slow.
