### ISSUE TITLE
Slicing with colon produces Vector instead of ComponentVector

### ISSUE THREAD

**Issue by baggepinnen** [jonniedie/ComponentArrays.jl#56]
I'm trying to get `ComponentVector` to work with `Optim.ParticleSwarm` and am facing the following issue: when slicing into a matrix where there are components along the first axis, the result is a regular vector
```julia
julia> A
4×10 ComponentMatrix{Float64} with axes Axis(a = 1:2, b = 3:4) × FlatAxis()
 0.0           0.0           0.0           …  0.0           0.0           0.0
 0.0           0.0           0.0              0.0           0.0           0.0
 6.92009e-310  6.92009e-310  6.92009e-310     6.92009e-310  6.92009e-310  6.92017e-310
 6.92009e-310  6.92009e-310  6.92009e-310     6.92009e-310  1.0e-323      6.92017e-310

julia> A[:,1]
4-element Vector{Float64}:
 0.0
 0.0
 6.92009e-310
 6.92009e-310
```
In this case, I believe it should be possible to return a `ComponentVector` even if I index the component dimension with `:`?

**Comment by jonniedie** [comment]
Yep, it should do that. This is a bug that must have been introduced when I recently changed the flat (non-symbolic) indexing behavior.

Although this highlights an issue that I’ve had since the beginning of ComponentArrays: Should non-symbolic indexing produce a view or a new array? Since named views are kinda the whole purpose of ComponentArrays, I always had it set up so *all* indexing creates a `view`. But this led to some bugs when interacting with other packages because the general expectation is that indexing an array in the “normal” way should always produce a new array. So I recently changed it so that indexing would only create views when symbolic indices are used. But this puts `A[:,1]` in a weird spot: It feels to me like `ComponentArray -> ComponentArray` operations like this should always use views, but that’s wrong for the above reasons and would continue to introduce bugs. So when I push this fix, it will be such that `@view A[:,1]` is needed if you want the result to be a `view`.

**Comment by baggepinnen** [comment]
I was expecting `A[:,1]` to return a copy, but with the type being a `ComponentVector`, so requiring `@view A[:,1]` to obtain a view feels in line with my expectations.

**Comment by baggepinnen** [comment]
Thanks for the fix! The PR to Optim is here
https://github.com/JuliaNLSolvers/Optim.jl/pull/883
I provided a naive implementation of 
```julia
Optim.similar_axis(x::ComponentArray, n) = x .* zeros(length(x), n)
```
which gives me 
```julia
ComponentMatrix{Float64} with axes Axis(a = 1:2, b = 3:4) × FlatAxis()
```
but I'm sure there's a better way?
