### ISSUE TITLE
Constructor for Axis

### ISSUE THREAD

**Issue by baggepinnen** [jonniedie/ComponentArrays.jl#84]
I'm struggling to figure out how to properly create an `Axis`

From a vector of symbols, `state_names`, I want to create an axis that can be used for the variable `x` and the matrix `A` in 
```julia
x' = A*x
```
I guess it would be possible to have a slurping constructor that accepts something like the following
```julia
julia>     ax_x = Axis(state_names...)
FlatAxis()
```
and internally dispatches to the `NamedTuple` so I do not have to figure out this awkward way of constructing such an `Axis`.
```julia
julia> ax_x = Axis((; (state_names .=> (1:sys.nx))...))
Axis(x1 = 1,)
```
Indeed, if I define 
```julia
function ComponentArrays.Axis(names::Symbol...)
    Axis((; (names .=> (1:length(names)))...))
end

julia>     ax_x = Axis(state_names...)
Axis(x1 = 1,)
```
I seem to get what I want :)

**Comment by jonniedie** [comment]
I guess for the case where each name corresponds to a scalar element, that makes sense. But most use cases for ComponentArrays are a little more complicated than that, so I've never really thought to define a convenience constructor for this case. Actually, it's been a while since I've given any thought to `Axis` constructors, since I generally don't use them (I usually create a prototype of a `ComponentVector` and use `getaxes`).
