### ISSUE TITLE
ArrayInterface.zeromatrix

### ISSUE THREAD

**Issue by baggepinnen** [jonniedie/ComponentArrays.jl#85]
It appeas as if `ArrayInterface.zeromatrix` does not propagate the type for a ComponentMatrix correctly.
```julia
julia> nsys.A
1×1 ComponentMatrix{Int64} with axes Axis(x1 = 1,) × Axis(x1 = 1,)
 1

julia> ArrayInterface.zeromatrix(nsys.A)
1×1 Matrix{Int64}:
 0
```

**Comment by jonniedie** [comment]
Yeah, I think that should error on the ArrayInterface side because it's not supposed to work for matrices. `zeromatrix` is a function that is meant to operate on `AbstractVector`s to create an `AbstractMatrix` of zeros and similar type. So calling it on an `AbstractMatrix` will first flatten out the matrix into a vector and then create a matrix by taking the outer product of the flattened vector.

You should be good just to use `zero(nsys.A)` here if you want to get a similar `ComponentMatrix` with zeroed entries.
