### ISSUE TITLE
Picking out column of matrix drops index

### ISSUE THREAD

**Issue by baggepinnen** [jonniedie/ComponentArrays.jl#88]
Here, I'm trying to get a single column from a ComponentMatrix and maintaining the name of the column. 
```julia
julia> s1.B
1×1 ComponentMatrix{Int64} with axes Axis(x = 1,) × Axis(u = 1,)
 1

julia> s1.B[:,1:1]
1×1 ComponentMatrix{Int64} with axes Axis(x = 1,) × FlatAxis()
 1
```
The axis has been modified to a flat axis. 

The purpose is indexing a statespace system with ComponentArrays maintaining the names of inputs and outputs. I have something like the following (which circumvents https://github.com/jonniedie/ComponentArrays.jl/issues/71)
```julia
function Base.getindex(sys::NamedStateSpace, i::NamedIndex, j::NamedIndex)
    i,j = iterable.((i, j))
    C = sys.C[:,1]
    B = sys.B[1,:]
    @show ii = [label2index(C, string(i))[] for i in i] # TODO: inefficient
    @show jj = [label2index(B, string(j))[] for j in j]

    return HeteroStateSpace(copy(sys.A), sys.B[:, jj], sys.C[ii, :], sys.D[ii, jj], sys.timeevol)
end
```
Here, all indexed axes of `B,C,D` are modified to `FlatAxis`.

**Comment by jonniedie** [comment]
Hm. Let me give this some thought. It's always been the case that indexing with a non-symbolic index dropped that axis to a `FlatAxis` in order to keep "normal" indexing fast. I don't think we can give that up because so many things ComponentArrays need to be used for rely on fast indexing in that way.

One option would be some kind of a wrapper for indices that are meant to retain their component names. I'll see what I can come up with, because having to use `label2index` is far from ideal.

**Comment by jonniedie** [comment]
This is the thought:

```julia
julia> cmat = ComponentMatrix([1 2 3; 4 5 6], Axis(a=1, b=2), Axis(x=1, y=2, z=3))
2×3 ComponentMatrix{Int64} with axes Axis(a = 1, b = 2) × Axis(x = 1, y = 2, z = 3)
 1  2  3
 4  5  6

julia> cmat[:, KeepIndex(3)]
2×1 ComponentMatrix{Int64} with axes Axis(a = 1, b = 2) × Axis(z = 1,)
 3
 6

julia> cmat[:, KeepIndex(:y)]
2×1 ComponentMatrix{Int64} with axes Axis(a = 1, b = 2) × Axis(y = 1,)
 2
 5
```
But it also needs to handle weird stuff like this:
```julia
julia> ca = ComponentArray(a=4, b=2, c=[2, 6], d=(a=[1, 5, 2], b=3))
ComponentVector{Int64}(a = 4, b = 2, c = [2, 6], d = (a = [1, 5, 2], b = 3))

julia> ca[KeepIndex(2:6)]
ComponentVector{Int64}(b = 2, c = [2, 6], d = (a = [1, 5]))
```
I haven't totally figured it out yet, but I think I'm, close. Once I get this, I might be able to figure out a way to handle #71 too.

**Comment by baggepinnen** [comment]
Sweet! Thanks for your continued efforts :) I realize it can get quite hairy with all fancy indexing this package supports, I'm really only using a trivial subset of it.

**Comment by jonniedie** [comment]
Alright, I made a `KeepIndex` wrapper that will retain the symbolic names for everything that is fully captured in the index range. Since I'm not sure when or if my docs are going to build, I'll just copy and paste that section here:


## Retaining component labels through index operations
Sometimes you might want to index into a `ComponentArray` without dropping the component name. Let's look at a new example with a more deeply nested structure:
```julia
julia> ca = ComponentArray(a=5, b=[4, 1], c=(a=2, b=[6, 30]))
ComponentVector{Int64}(a = 5, b = [4, 1], c = (a = 2, b = [6, 30]))
```
If we wanted to get the `b` component while keeping the name, we can use the `KeepIndex` wrapper around our index:
```julia
julia> ca[KeepIndex(:b)]
ComponentVector{Int64}(b = [4, 1])
```
Now instead of just returning a plain `Vector`, this returns a `ComponentVector` that keeps the `b` name. Of course, this is still compatible with `view`s, so we could have done `@view ca[KeepIndex(:b)]` if we wanted to retain the view into the origianl.

Similarly, we can use plain indexes like ranges or integers and they will keep the names of any components they capture:
```julia
julia> ca[KeepIndex(1)]
ComponentVector{Int64}(a = 5)

julia> ca[KeepIndex(2:3)]
ComponentVector{Int64}(b = [4, 1])

julia> ca[KeepIndex(1:3)]
ComponentVector{Int64}(a = 5, b = [4, 1])

julia> ca[KeepIndex(2:end)]
ComponentVector{Int64}(b = [4, 1], c = (a = 2, b = [6, 30]))
```
But what if our range doesn't capture a full component? We can see below that using `KeepIndex` on the first five elements returns a `ComponentVector` with those elements but only the `a` and `b` names, since the `c` component wasn't fully captured. 
```julia
julia> ca[KeepIndex(1:5)]
5-element ComponentVector{Int64} with axis Axis(a = 1, b = 2:3):
 5
 4
 1
 2
 6
```

**Comment by jonniedie** [comment]
Or course, you can also `@view ca[KeepIndex(...` too.
